name: Java Build, Run and Test Lab03

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  show-current-path:
    name: shows current file path
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print path
        run: pwd
        
  run-test-java:
    name: run java tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Run tests with Maven
        run: mvn test
        
    
