name: Java build, run and test Lab03

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-path:
    name: show current file path
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print current file path
        run: pwd

  build-test-java:
      name: run java test
      runs-on: ubuntu-latest

      steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up jdk 23
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: build with maven
        run: mvn clean install -DskipTests
      - name: run tests
        run: mvn test

  
